# Cross Validation

## Decision Trees Regression

In [21]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_boston
from sklearn.datasets import load_iris

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings('ignore')

In [46]:
X, y = load_boston(return_X_y=True)
print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

print(X_train.shape)
print(model.score(X_test, y_test))
print(model.score(X_train, y_train))

(506, 13)
(506,)
(404, 13)
0.8056826797419983
1.0


In [43]:
scores=cross_val_score(model, X_train, y_train, cv=5)
scores

array([0.9083609 , 0.81306436, 0.73749838, 0.70233567, 0.4756353 ])

In [44]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.73 accuracy with a standard deviation of 0.14


## Decision Trees Classification

In [51]:
X, y = load_iris(return_X_y=True)
print(X.shape)
print(y.shape)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
mo= DecisionTreeClassifier()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))
print(model.score(X_train, y_train))

(150, 4)
(150,)
0.9063962558502341
1.0


In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

<b> multi class problem 

In [9]:
set(y)

{0, 1, 2}

In [49]:
scores=cross_val_score(model, X_train, y_train, cv=5)
scores

array([0.84158416, 0.92282958, 0.92771084, 0.94392523, 1.        ])

In [50]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.93 accuracy with a standard deviation of 0.05


In [12]:
y_test

array([1, 0, 1, 2, 0, 0, 2, 2, 1, 0, 2, 2, 0, 1, 0, 2, 1, 1, 2, 2, 0, 2,
       1, 2, 1, 1, 0, 1, 0, 2])

In [13]:
y_pred = cross_val_predict(model, X_test, y_test, cv=5)
y_pred

array([1., 0., 1., 2., 0., 0., 2., 1., 1., 0., 2., 2., 0., 1., 0., 2., 1.,
       1., 2., 2., 0., 2., 1., 2., 1., 1., 0., 1., 0., 1.])

### Models Comparision

In [52]:
model1 = DecisionTreeRegressor()

model2 = LinearRegression()

model3 = KNeighborsRegressor()

model_pipeline = [model1, model2, model3]
model_names = ['Regression Tree', 'Linear Regression', 'KNN']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=5))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Regression Tree': 0.9085359785773559, 'Linear Regression': 0.9102374331357621, 'KNN': 0.9337777261012963}
